// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1m9tkTGEYVGL7XL_or93vmm7q75QYu50',
    appId: '1:706212562644:web:dcb1e6c440861ccc19dd41',
    messagingSenderId: '706212562644',
    projectId: 'medical-app-338ec',
    authDomain: 'medical-app-338ec.firebaseapp.com',
    storageBucket: 'medical-app-338ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS2aejv7GoH97TOrpBY6C_PnVfiHU7BLA',
    appId: '1:706212562644:android:0c686632bc5afc9119dd41',
    messagingSenderId: '706212562644',
    projectId: 'medical-app-338ec',
    storageBucket: 'medical-app-338ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoeZxgp9WXunnh-5H_YU6q3M34cXXt-1M',
    appId: '1:706212562644:ios:7732556e253a3fe519dd41',
    messagingSenderId: '706212562644',
    projectId: 'medical-app-338ec',
    storageBucket: 'medical-app-338ec.firebasestorage.app',
    iosBundleId: 'com.example.sehatfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoeZxgp9WXunnh-5H_YU6q3M34cXXt-1M',
    appId: '1:706212562644:ios:7732556e253a3fe519dd41',
    messagingSenderId: '706212562644',
    projectId: 'medical-app-338ec',
    storageBucket: 'medical-app-338ec.firebasestorage.app',
    iosBundleId: 'com.example.sehatfile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1m9tkTGEYVGL7XL_or93vmm7q75QYu50',
    appId: '1:706212562644:web:0facdaddfb6e375b19dd41',
    messagingSenderId: '706212562644',
    projectId: 'medical-app-338ec',
    authDomain: 'medical-app-338ec.firebaseapp.com',
    storageBucket: 'medical-app-338ec.firebasestorage.app',
  );
}
